### ISSUE TITLE
Deprecated scipy integrators

### ISSUE THREAD

**Issue by damonge** [DarkQuestCosmology/dark_emulator_public#28]
It seems the code uses scipy numerical integration methods that have now been deprecated as of v1.14. This causes some of our unit tests in CCL to fail unless we make sure to use old versions of scipy (see e.g. this [run](https://github.com/LSSTDESC/CCL/actions/runs/11834707209/job/32975944331)).

An example of offending code is [this](https://github.com/DarkQuestCosmology/dark_emulator_public/blob/46df5972509624e2eeadc2bf3ac528b02333a7e2/dark_emulator/model_hod/hod_interface.py#L18)

**Comment by HironaoMiyatake** [comment]
@damonge Sorry for this delayed response. I'm now working on this. @nishimichi , I am now using python 3.12.2 and scipy 1.15.2, and found that this error.
```
File [/data/miyatake/dark_emulator_public/dark_emulator/darkemu/cosmo_util.py:5](https://localhost:7777/data/miyatake/dark_emulator_public/dark_emulator/darkemu/cosmo_util.py#line=4)
      3 import logging
      4 from scipy import integrate
----> 5 from scipy.misc import derivative
      6 from collections import OrderedDict
      7 import logging

ImportError: cannot import name 'derivative' from 'scipy.misc' ([/home/miyatake/.conda/envs/dark_emulator/lib/python3.12/site-packages/scipy/misc/__init__.py](https://localhost:7777/user/miyatake/lab/workspaces/auto-f/tree/data/dark_emulator_public/docs/.conda/envs/dark_emulator/lib/python3.12/site-packages/scipy/misc/__init__.py))
``` 
, so we might need more fixes. I'll keep you updated.

**Comment by ryusei172525** [comment]
At the moment, requirements.txt should look like this
```
# requirements for dark emulator modules
numpy
scipy==1.13
george
# additionnal requirements for hod modules
#colossus
```

**Comment by nikosarcevic** [comment]
Hi, all

may I ask if this can be fixed?

Also, since this is the derivative code, I would like to advertise [the derivative code we have been working on](https://github.com/derivkit/derivkit)

If you want to explore this option, we would love to help with the implementation (it would be extremely easy from what I see in cosmo_util.py)

Best
Niko, Matthijs and Cynthia

**Comment by andrejdvornik** [comment]
@nikosarcevic, this was fixed in PR #29, but not yet released as new version

**Comment by nikosarcevic** [comment]
Gotcha!

**Comment by andrejdvornik** [comment]
There are still two cases of `scipy.trapz` in `de_interface.py` (line 571 and 116)  and `hmf.py` (line 105)

**Comment by 0satoken** [comment]
Thanks @andrejdvornik for pointing this out. I created PR #30 to fix the issue.

**Comment by carlosggarcia** [comment]
Hi all! May I ask what the status of these fixes is? CCL tests are still failing due to the `derivative`. We are going to try using `master` for now but I fear that the `trapz` issue will appear in the near future, so a release with these fixes would be useful.

I am happy to help with the update if needed. 
Thanks!
